name: Execute Slack RPA

on:
  schedule:
    # Se ejecuta cada hora (minuto 0), de lunes a viernes (1-5)
    - cron: '0 * * * 1-5'
  workflow_dispatch:

jobs:
  run-rpa:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar RPA
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          ID_SMOKE_CHANNEL: ${{ secrets.ID_SMOKE_CHANNEL }}
          ID_QA_CHANNEL: ${{ secrets.ID_QA_CHANNEL }}
        run: python slack_rpa.py

      - name: Guardar progreso (Persistencia)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add rpa_state.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "ü§ñ RPA: Rotaci√≥n de encargado" && git push)
